#source - https://github.com/ghoshsuman845/List-of-Top-Unicorn-Startups-India
list_of_unicorns = [
    {'company_name': '5ire', 'company_sector': 'B2C Fintech', 'company_linkedin_url': 'https://www.linkedin.com/company/5irechain/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Acko', 'company_sector': 'B2C Fintech', 'company_linkedin_url': 'https://www.linkedin.com/company/acko/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Amagi', 'company_sector': 'B2B SaaS', 'company_linkedin_url': 'https://www.linkedin.com/company/amagicorporation/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Apna', 'company_sector': 'B2B Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/apnahq/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Ather', 'company_sector': 'B2C Mobility & Transportation', 'company_linkedin_url': 'https://www.linkedin.com/company/ather-energy/', 'company_category': 'Unicorn'}, 
    {'company_name': 'BharatPe', 'company_sector': 'B2C Fintech', 'company_linkedin_url': 'https://www.linkedin.com/company/bharatpe/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Bigbasket', 'company_sector': 'B2C Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/bigbasket-com/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Billdesk', 'company_sector': 'B2B Fintech', 'company_linkedin_url': 'https://www.linkedin.com/company/billdesk/', 'company_category': 'Unicorn'}, 
    {'company_name': 'BlackBuck', 'company_sector': 'B2B Logistics', 'company_linkedin_url': 'https://www.linkedin.com/company/blackbuck/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Blinkit (ex-Grofers)', 'company_sector': 'B2C Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/letsblinkit/', 'company_category': 'Unicorn'}, 
    {'company_name': 'BrowserStack', 'company_sector': 'B2B SaaS', 'company_linkedin_url': 'https://www.linkedin.com/company/browserstack/', 'company_category': 'Unicorn'}, 
    {'company_name': "Byju's", 'company_sector': 'B2C Edtech', 'company_linkedin_url': 'https://www.linkedin.com/company/byjus/', 'company_category': 'Unicorn'}, 
    {'company_name': 'CarDekho', 'company_sector': 'B2C Mobility & Transportation', 'company_linkedin_url': 'https://www.linkedin.com/company/cardekhogroup/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Cars24', 'company_sector': 'B2C Mobility & Transportation', 'company_linkedin_url': 'https://www.linkedin.com/company/cars24/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Chargebee', 'company_sector': 'B2B SaaS', 'company_linkedin_url': 'https://www.linkedin.com/company/chargebee/', 'company_category': 'Unicorn'},
    {'company_name': 'CoinDCX', 'company_sector': 'B2C Fintech', 'company_linkedin_url': 'https://www.linkedin.com/company/coindcx/', 'company_category': 'Unicorn'}, 
    {'company_name': 'CoinSwitch Kuber', 'company_sector': 'B2C Fintech', 'company_linkedin_url': 'https://www.linkedin.com/company/coinswitch/', 'company_category': 'Unicorn'}, 
    {'company_name': 'CommerceIQ', 'company_sector': 'B2B SaaS', 'company_linkedin_url': 'https://www.linkedin.com/company/commerceiq/', 'company_category': 'Unicorn'}, 
    {'company_name': 'CRED', 'company_sector': 'B2C Fintech', 'company_linkedin_url': 'https://www.linkedin.com/company/credapp/', 'company_category': 'Unicorn'},
    {'company_name': 'Cult.fit', 'company_sector': 'B2C Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/cult.fit/', 'company_category': 'Unicorn'}, 
    {'company_name': 'DailyHunt', 'company_sector': 'B2C Media & Entertainment', 'company_linkedin_url': 'https://www.linkedin.com/company/dailyhunt/', 'company_category': 'Unicorn'},
    {'company_name': 'Darwinbox', 'company_sector': 'B2B SaaS', 'company_linkedin_url': 'https://www.linkedin.com/company/darwinbox/', 'company_category': 'Unicorn'}, 
    {'company_name': 'DealShare', 'company_sector': 'B2C Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/dealshare-in/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Delhivery', 'company_sector': 'B2B Logistics', 'company_linkedin_url': 'https://www.linkedin.com/company/delhivery/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Digit Insurance', 'company_sector': 'B2C Fintech', 'company_linkedin_url': 'https://www.linkedin.com/company/godigit/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Dream Sports', 'company_sector': 'B2C Media & Entertainment', 'company_linkedin_url': 'https://www.linkedin.com/company/dreamsports/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Droom', 'company_sector': 'B2C Mobility & Transportation', 'company_linkedin_url': 'https://www.linkedin.com/company/droom-in/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Druva', 'company_sector': 'B2B SaaS', 'company_linkedin_url': 'https://www.linkedin.com/company/druva/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Easemytrip.com', 'company_sector': 'B2C Mobility & Transportation', 'company_linkedin_url': 'https://www.linkedin.com/company/easemytrip-com/', 'company_category': 'Unicorn'}, 
    {'company_name': 'ElasticRun', 'company_sector': 'B2B Logistics', 'company_linkedin_url': 'https://www.linkedin.com/company/elasticrun/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Eruditus', 'company_sector': 'B2C Edtech', 'company_linkedin_url': 'https://www.linkedin.com/company/eruditus-education/', 'company_category': 'Unicorn'}, 
    {'company_name': 'FirstCry', 'company_sector': 'B2C Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/firstcry/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Five Star Business Finance', 'company_sector': 'B2B Fintech', 'company_linkedin_url': 'https://www.linkedin.com/company/five-star-business-finance/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Flipkart', 'company_sector': 'B2C Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/flipkart/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Fractal', 'company_sector': 'B2B SaaS', 'company_linkedin_url': 'https://www.linkedin.com/company/fractal-analytics/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Freshworks', 'company_sector': 'B2B SaaS', 'company_linkedin_url': 'https://www.linkedin.com/company/freshworks-inc/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Games24x7', 'company_sector': 'B2C Media & Entertainment', 'company_linkedin_url': 'https://www.linkedin.com/company/games24x7-private-limited/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Glance Inmobi', 'company_sector': 'B2C Media & Entertainment', 'company_linkedin_url': 'https://www.linkedin.com/company/inmobi/', 'company_category': 'Unicorn'}, 
    {'company_name': 'GlobalBees', 'company_sector': 'B2C Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/globalbees/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Groww', 'company_sector': 'B2C Fintech', 'company_linkedin_url': 'https://www.linkedin.com/company/groww.in/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Gupshup', 'company_sector': 'B2B SaaS', 'company_linkedin_url': 'https://www.linkedin.com/company/gupshup/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Hasura', 'company_sector': 'B2B SaaS', 'company_linkedin_url': 'https://www.linkedin.com/company/hasura/', 'company_category': 'Unicorn'}, 
    {'company_name': 'HighRadius', 'company_sector': 'B2B Fintech', 'company_linkedin_url': 'https://www.linkedin.com/company/highradius/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Hike', 'company_sector': 'B2C Media & Entertainment', 'company_linkedin_url': 'https://www.linkedin.com/company/hike/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Icertis', 'company_sector': 'B2B SaaS', 'company_linkedin_url': 'https://www.linkedin.com/company/icertis/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Incred', 'company_sector': 'B2C Fintech', 'company_linkedin_url': 'https://www.linkedin.com/company/incredfinancialservices', 'company_category': 'Unicorn'}, 
    {'company_name': 'Infra.Market', 'company_sector': 'B2B Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/inframarket/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Innovaccer', 'company_sector': 'B2C Healthtech', 'company_linkedin_url': 'https://www.linkedin.com/company/innovaccer/', 'company_category': 'Unicorn'}, 
    {'company_name': 'LEAD', 'company_sector': 'B2C Edtech', 'company_linkedin_url': 'https://www.linkedin.com/company/lead-school/', 'company_category': 'Unicorn'}, 
    {'company_name': 'LeadSquared', 'company_sector': 'B2B SaaS', 'company_linkedin_url': 'https://www.linkedin.com/company/leadsquared/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Lenskart', 'company_sector': 'B2C Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/lenskart-com/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Licious', 'company_sector': 'B2C Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/licious/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Livspace', 'company_sector': 'B2C Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/livspace/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Makemytrip', 'company_sector': 'B2C Mobility & Transportation', 'company_linkedin_url': 'https://www.linkedin.com/company/makemytrip.com/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Mamaearth', 'company_sector': 'B2C Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/mama-earth-in/', 'company_category': 'Unicorn'}, 
    {'company_name': 'MapMyIndia', 'company_sector': 'B2B SaaS', 'company_linkedin_url': 'https://www.linkedin.com/company/mapmyindia/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Meesho', 'company_sector': 'B2C Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/meesho/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Mensa Brands', 'company_sector': 'B2C Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/mensa-brands/', 'company_category': 'Unicorn'}, 
    {'company_name': 'MindTickle', 'company_sector': 'B2B SaaS', 'company_linkedin_url': 'https://www.linkedin.com/company/mindtickle/', 'company_category': 'Unicorn'}, 
    {'company_name': 'MobiKwik', 'company_sector': 'B2C Fintech', 'company_linkedin_url': 'https://www.linkedin.com/company/mobikwik/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Moglix', 'company_sector': 'B2B Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/moglix/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Mohalla Tech (Moj)', 'company_sector': 'B2C Media & Entertainment', 'company_linkedin_url': 'https://www.linkedin.com/company/mojindia/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Molbio Diagnostics', 'company_sector': 'B2C Healthtech', 'company_linkedin_url': 'https://www.linkedin.com/company/molbio-diagnostics/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Moneyview', 'company_sector': 'B2C Fintech', 'company_linkedin_url': 'https://www.linkedin.com/company/money-view/', 'company_category': 'Unicorn'}, 
    {'company_name': 'MPL', 'company_sector': 'B2C Media & Entertainment', 'company_linkedin_url': 'https://www.linkedin.com/company/mobile-premier-league/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Mu Sigma', 'company_sector': 'B2B SaaS', 'company_linkedin_url': 'https://www.linkedin.com/company/mu-sigma/', 'company_category': 'Unicorn'}, 
    {'company_name': 'MyGlamm (Good Glamm Group)', 'company_sector': 'B2C Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/myglamm/', 'company_category': 'Unicorn'}, 
    {'company_name': 'NoBroker', 'company_sector': 'B2C Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/nobroker-in/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Nykaa', 'company_sector': 'B2C Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/nykaa-com/', 'company_category': 'Unicorn'}, 
    {'company_name': 'OfBusiness', 'company_sector': 'B2B SaaS', 'company_linkedin_url': 'https://www.linkedin.com/company/ofbusiness/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Ola', 'company_sector': 'B2C Mobility & Transportation', 'company_linkedin_url': 'https://www.linkedin.com/company/olacabs-com/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Ola Electric', 'company_sector': 'B2C Fintech', 'company_linkedin_url': 'https://www.linkedin.com/company/olaelectric/', 'company_category': 'Unicorn'}, 
    {'company_name': 'OneCard', 'company_sector': 'B2C Fintech', 'company_linkedin_url': 'https://www.linkedin.com/showcase/onecard-app/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Open', 'company_sector': 'B2B Fintech', 'company_linkedin_url': 'https://www.linkedin.com/company/bankwithopen/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Oxyzo', 'company_sector': 'B2B Fintech', 'company_linkedin_url': 'https://www.linkedin.com/company/oxyzo/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Oyo', 'company_sector': 'B2C Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/oyo-rooms/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Paytm', 'company_sector': 'B2C Fintech', 'company_linkedin_url': 'https://www.linkedin.com/company/paytm/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Paytm Mall', 'company_sector': 'B2C Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/paytmmall/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Perfios', 'company_sector': 'B2B Fintech', 'company_linkedin_url': 'https://www.linkedin.com/company/perfios/', 'company_category': 'Unicorn'}, 
    {'company_name': 'PharmEasy', 'company_sector': 'B2C Healthtech', 'company_linkedin_url': 'https://www.linkedin.com/company/pharmeasy/', 'company_category': 'Unicorn'}, 
    {'company_name': 'PhonePe', 'company_sector': 'B2C Fintech', 'company_linkedin_url': 'https://www.linkedin.com/company/phonepe-internet/', 'company_category': 'Unicorn'}, 
    {'company_name': 'PhysicsWallah', 'company_sector': 'B2C Edtech', 'company_linkedin_url': 'https://www.linkedin.com/company/physicswallah/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Pine Labs', 'company_sector': 'B2B Fintech', 'company_linkedin_url': 'https://www.linkedin.com/company/pinelabs/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Policy Bazaar', 'company_sector': 'B2C Fintech', 'company_linkedin_url': 'https://www.linkedin.com/company/policybazaar/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Polygon (Formerly Matic Network)', 'company_sector': 'B2C Fintech', 'company_linkedin_url': 'https://www.linkedin.com/company/polygonlabs/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Postman', 'company_sector': 'B2B SaaS', 'company_linkedin_url': 'https://www.linkedin.com/company/postman-platform/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Pristyn Care', 'company_sector': 'B2C Healthtech', 'company_linkedin_url': 'https://www.linkedin.com/company/pristyncare/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Purplle', 'company_sector': 'B2C Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/purplle-com/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Quikr', 'company_sector': 'B2C Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/quikr/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Rapido', 'company_sector': 'B2C Mobility & Transportation', 'company_linkedin_url': 'https://www.linkedin.com/company/rapido-bike/', 'company_category': 'Unicorn'}, 
    {'company_name': 'RateGain', 'company_sector': 'B2B SaaS', 'company_linkedin_url': 'https://www.linkedin.com/company/rategain/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Razorpay', 'company_sector': 'B2B Fintech', 'company_linkedin_url': 'https://www.linkedin.com/company/razorpay/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Rebel Foods', 'company_sector': 'B2C Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/rebel-foods/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Renew Power', 'company_sector': 'B2B Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/renew-power-apac/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Rivigo', 'company_sector': 'B2B Logistics', 'company_linkedin_url': 'https://www.linkedin.com/company/rivigo/', 'company_category': 'Unicorn'}, 
    {'company_name': 'ShareChat', 'company_sector': 'B2C Media & Entertainment', 'company_linkedin_url': 'https://www.linkedin.com/company/sharechat/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Shiprocket', 'company_sector': 'B2B Logistics', 'company_linkedin_url': 'https://www.linkedin.com/company/shiprocket/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Shopclues', 'company_sector': 'B2C Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/shopclues/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Slice', 'company_sector': 'B2C Fintech', 'company_linkedin_url': 'https://www.linkedin.com/company/sliceit/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Snapdeal', 'company_sector': 'B2C Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/snapdeal/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Spinny', 'company_sector': 'B2C Mobility & Transportation', 'company_linkedin_url': 'https://www.linkedin.com/company/spinny/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Tata 1mg', 'company_sector': 'B2C Healthtech', 'company_linkedin_url': 'https://www.linkedin.com/company/1mg/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Udaan', 'company_sector': 'B2B Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/udaan/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Unacademy', 'company_sector': 'B2C Edtech', 'company_linkedin_url': 'https://www.linkedin.com/company/unacademy/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Uniphore', 'company_sector': 'B2B SaaS', 'company_linkedin_url': 'https://www.linkedin.com/company/uniphore/', 'company_category': 'Unicorn'}, 
    {'company_name': 'upGrad', 'company_sector': 'B2C Edtech', 'company_linkedin_url': 'https://www.linkedin.com/company/upgrad/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Upstox', 'company_sector': 'B2C Fintech', 'company_linkedin_url': 'https://www.linkedin.com/company/upstox/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Urban Company', 'company_sector': 'B2C Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/urbancompany/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Vedantu', 'company_sector': 'B2C Edtech', 'company_linkedin_url': 'https://www.linkedin.com/company/vedantu/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Verse Innovation', 'company_sector': 'B2C Media & Entertainment', 'company_linkedin_url': 'https://www.linkedin.com/company/verse-innovation/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Xpressbees', 'company_sector': 'B2B Logistics', 'company_linkedin_url': 'https://www.linkedin.com/company/xpressbees/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Yubi (Formerly CredAvenue)', 'company_sector': 'B2B Fintech', 'company_linkedin_url': 'https://www.linkedin.com/company/go-yubi/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Zenoti', 'company_sector': 'B2B SaaS', 'company_linkedin_url': 'https://www.linkedin.com/company/zenoti/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Zepto', 'company_sector': 'B2C Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/zeptonow/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Zerodha', 'company_sector': 'B2C Fintech', 'company_linkedin_url': 'https://www.linkedin.com/company/zerodha/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Zeta', 'company_sector': 'B2B Fintech', 'company_linkedin_url': 'https://www.linkedin.com/company/zetasuite/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Zetwerk', 'company_sector': 'B2B Fintech', 'company_linkedin_url': 'https://www.linkedin.com/company/zetwerk/', 'company_category': 'Unicorn'}, 
    {'company_name': 'Zomato', 'company_sector': 'B2C Commerce', 'company_linkedin_url': 'https://www.linkedin.com/company/zomato/', 'company_category': 'Unicorn'}
    ]