#source - https://github.com/ghoshsuman845/List-of-Top-Unicorn-Startups-India
list_of_unicorns = [
    {"name": "Zepto", "url": "https://www.linkedin.com/company/zeptonow/"},
    {"name": "Molbio Diagnostics", "url": "https://www.linkedin.com/company/molbio-diagnostics/"},
    {"name": "Tata 1mg", "url": "https://www.linkedin.com/company/1mg/"},
    {"name": "Shiprocket", "url": "https://www.linkedin.com/company/shiprocket/"},
    {"name": "5ire", "url": "https://www.linkedin.com/company/5irechain/"},
    {"name": "OneCard", "url": "https://www.linkedin.com/showcase/onecard-app/"},
    {"name": "PhysicsWallah", "url": "https://www.linkedin.com/company/physicswallah/"},
    {"name": "LeadSquared", "url": "https://www.linkedin.com/company/leadsquared/"},
    {"name": "ElasticRun", "url": "https://www.linkedin.com/company/elasticrun/"},
    {"name": "LEAD", "url": "https://www.linkedin.com/company/lead-school/"},
    {"name": "Purplle", "url": "https://www.linkedin.com/company/purplle-com/"},
    {"name": "DealShare", "url": "https://www.linkedin.com/company/dealshare-in/"},
    {"name": "Xpressbees", "url": "https://www.linkedin.com/company/xpressbees/"},
    {"name": "Open", "url": "https://www.linkedin.com/company/bankwithopen/"},
    {"name": "Games24x7", "url": "https://www.linkedin.com/company/games24x7-private-limited/"},
    {"name": "Amagi", "url": "https://www.linkedin.com/company/amagicorporation/"},
    {"name": "Fractal", "url": "https://www.linkedin.com/company/fractal-analytics/"},
    {"name": "Darwinbox", "url": "https://www.linkedin.com/company/darwinbox/"},
    {"name": "Livspace", "url": "https://www.linkedin.com/company/livspace/"},
    {"name": "Uniphore", "url": "https://www.linkedin.com/company/uniphore/"},
    {"name": "Hasura", "url": "https://www.linkedin.com/company/hasura/"},
    {"name": "Yubi (Formerly CredAvenue)", "url": "https://www.linkedin.com/company/go-yubi/"},
    {"name": "CommerceIQ", "url": "https://www.linkedin.com/company/commerceiq/"},
    {"name": "Oxyzo", "url": "https://www.linkedin.com/company/oxyzo/"},
    {"name": "Moglix", "url": "https://www.linkedin.com/company/moglix/"},
    {"name": "NoBroker", "url": "https://www.linkedin.com/company/nobroker-in/"},
    {"name": "MobiKwik", "url": "https://www.linkedin.com/company/mobikwik/"},
    {"name": "Spinny", "url": "https://www.linkedin.com/company/spinny/"},
    {"name": "MPL", "url": "https://www.linkedin.com/company/mobile-premier-league/"},
    {"name": "Acko", "url": "https://www.linkedin.com/company/acko/"},
    {"name": "ShareChat", "url": "https://www.linkedin.com/company/sharechat/"},
    {"name": "Eruditus", "url": "https://www.linkedin.com/company/eruditus-education/"},
    {"name": "upGrad", "url": "https://www.linkedin.com/company/upgrad/"},
    {"name": "Apna", "url": "https://www.linkedin.com/company/apnahq/"},
    {"name": "Urban Company", "url": "https://www.linkedin.com/company/urbancompany/"},
    {"name": "BharatPe", "url": "https://www.linkedin.com/company/bharatpe/"},
    {"name": "CarDekho", "url": "https://www.linkedin.com/company/cardekhogroup/"},
    {"name": "Licious", "url": "https://www.linkedin.com/company/licious/"},
    {"name": "Zetwerk", "url": "https://www.linkedin.com/company/zetwerk/"},
    {"name": "Meesho", "url": "https://www.linkedin.com/company/meesho/"},
    {"name": "Blinkit (ex-Grofers)", "url": "https://www.linkedin.com/company/letsblinkit/"},
    {"name": "Pristyn Care", "url": "https://www.linkedin.com/company/pristyncare/"},
    {"name": "Vedantu", "url": "https://www.linkedin.com/company/vedantu/"},
    {"name": "Upstox", "url": "https://www.linkedin.com/company/upstox/"},
    {"name": "Slice", "url": "https://www.linkedin.com/company/sliceit/"},
    {"name": "CRED", "url": "https://www.linkedin.com/company/credapp/"},
    {"name": "Cult.fit", "url": "https://www.linkedin.com/company/cult.fit/"},
    {"name": "Mamaearth", "url": "https://www.linkedin.com/company/mama-earth-in/"},
    {"name": "Infra.Market", "url": "https://www.linkedin.com/company/inframarket/"},
    {"name": "Five Star Business Finance", "url": "https://www.linkedin.com/company/five-star-business-finance/"},
    {"name": "OfBusiness", "url": "https://www.linkedin.com/company/ofbusiness/"},
    {"name": "CoinSwitch Kuber", "url": "https://www.linkedin.com/company/coinswitch/"},
    {"name": "CoinDCX", "url": "https://www.linkedin.com/company/coindcx/"},
    {"name": "BlackBuck", "url": "https://www.linkedin.com/company/blackbuck/"},
    {"name": "Droom", "url": "https://www.linkedin.com/company/droom-in/"},
    {"name": "PharmEasy", "url": "https://www.linkedin.com/company/pharmeasy/"},
    {"name": "MyGlamm (Good Glamm Group)", "url": "https://www.linkedin.com/company/myglamm/"},
    {"name": "Digit Insurance", "url": "https://www.linkedin.com/company/godigit/"},
    {"name": "Innovaccer", "url": "https://www.linkedin.com/company/innovaccer/"},
    {"name": "Groww", "url": "https://www.linkedin.com/company/groww.in/"},
    {"name": "Gupshup", "url": "https://www.linkedin.com/company/gupshup/"},
    {"name": "Chargebee", "url": "https://www.linkedin.com/company/chargebee/"},
    {"name": "Zeta", "url": "https://www.linkedin.com/company/zetasuite/"},
    {"name": "BrowserStack", "url": "https://www.linkedin.com/company/browserstack/"},
    {"name": "Mohalla Tech (Moj)", "url": "https://www.linkedin.com/company/mojindia/"},
    {"name": "Polygon (Formerly Matic Network)", "url": "https://www.linkedin.com/company/polygonlabs/"},
    {"name": "MindTickle", "url": "https://www.linkedin.com/company/mindtickle/"},
    {"name": "Rebel Foods", "url": "https://www.linkedin.com/company/rebel-foods/"},
    {"name": "Mensa Brands", "url": "https://www.linkedin.com/company/mensa-brands/"},
    {"name": "GlobalBees", "url": "https://www.linkedin.com/company/globalbees/"},
    {"name": "DailyHunt", "url": "https://www.linkedin.com/company/dailyhunt/"},
    {"name": "Unacademy", "url": "https://www.linkedin.com/company/unacademy/"},
    {"name": "Cars24", "url": "https://www.linkedin.com/company/cars24/"},
    {"name": "Glance, Inmobi", "url": "https://www.linkedin.com/company/inmobi/"},
    {"name": "Razorpay", "url": "https://www.linkedin.com/company/razorpay/"},
    {"name": "Zerodha", "url": "https://www.linkedin.com/company/zerodha/"},
    {"name": "PhonePe", "url": "https://www.linkedin.com/company/phonepe-internet/"},
    {"name": "FirstCry", "url": "https://www.linkedin.com/company/firstcry/"},
    {"name": "Nykaa", "url": "https://www.linkedin.com/company/nykaa-com/"},
    {"name": "Pine Labs", "url": "https://www.linkedin.com/company/pinelabs/"},
    {"name": "HighRadius", "url": "https://www.linkedin.com/company/highradius/"},
    {"name": "Verse Innovation", "url": "https://www.linkedin.com/company/verse-innovation/"},
    {"name": "Zenoti", "url": "https://www.linkedin.com/company/zenoti/"}
    # Add more companies as needed
]